version: '3.7'
services:
  backend:
    build: ./backend
    networks:
      - app-network
    depends_on:
      - database

  database:
    build: ./database
    networks:
      - app-network
    volumes: 
      - db_data:/var/lib/postgresql/data

  httpd:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
      
volumes:
  db_data:
    driver: local

networks:
  app-network: