---
# tasks file for roles/proxy
- name: Run proxy
  docker_container: 
    name: proxy
    image: jrocpe/tp-devops-cpe-proxy:latest
    ports:
      - "80:80"
    networks:
      - name: "app-network"
