name: Ansible deployment
on:
  workflow_call:
    secrets:
      VAULTPASS:
        required: true
# on:
#   push:
#     branches: 
#       - main
#       - develop

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==2.9.2 requests
      - name: run exporters playbook
        env:
          VAULTPASS: ${{ secrets.VAULTPASS }}
        run: |
          cd ansible
          chmod 400 id_rsa
          sudo docker build -t ansible . 
          sudo docker run -e "VAULT_PASS=$VAULTPASS" ansible