name: Ansible deployment
on:
  push:
    branches: 
      - main
      - develop

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==2.9.2 requests
      - name: set ansible config secrets
        env:
          DO_SSH_KEY: ${{ secrets.ANSIBLE_SSH_KEY }}
        run: |
          echo "$DO_SSH_KEY" > .ssh/id_rsa.bin
          chmod 600 .ssh/id_rsa.bin
          head -n 2 .ssh/id_rsa.bin
      - name: run exporters playbook
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml