name: CI devops 2022 CPE
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true  
jobs:
  # Define job to build and publish docker image
  push-backend:
    runs-on: ubuntu-latest
    
    # Steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to DockerHub to push images later
      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          # Relative path to the place where source code with Dockerfile is located
          context: ./backend
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-cpe-backend
          # Build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

  push-database:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./database  # Launch build-and-test-app job when there are changes on database directory.
    
    # Steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to DockerHub to push images later
      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_TOKEN }}

      # Same for database
      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          context: ./database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-cpe-database
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

  push-frontend:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./frontend  # Launch build-and-test-app job when there are changes on frontend directory.
    
    # Steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to DockerHub to push images later
      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_TOKEN }}

      # Same for frontend
      - name: Build image and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-cpe-frontend
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
  deploy-with-ansible:
    runs-on: ubuntu-latest
    needs:
      - push-frontend
      - push-backend
      - push-database
    uses: ./.github/workflows/.ansible.yml